const ProCard = [
    {
        title:"Nutritions",
        image:"images/Pharmacy.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"pharmacy",
    },
    {
        title:"Medicine",
        image:"images/Medicine.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"pharmacy",
    },
    {
        title:"Nutritions",
        image:"images/Pharmacy.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"pharmacy",
    },
    {
        title:"Nutritions",
        image:"images/Pharmacy.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"pharmacy",
    },
    {
        title:"Hand Gloves",
        image:"images/Hand Gloves.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"Gloves",
    },
    {
        title:"Hand Gloves",
        image:"images/Hand Gloves.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"Gloves",
    },
    {
        title:"Hand Gloves",
        image:"images/Hand Gloves.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"Gloves",
    },
    {
        title:"Hand Gloves",
        image:"images/Hand Gloves.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"Gloves",
    },
    {
        title:"Hand Gloves",
        image:"images/Hand Gloves.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"Gloves",
    },
    {
        title:"Hand Gloves",
        image:"images/Hand Gloves.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"Gloves",
    },
    {
        title:"Hand Gloves",
        image:"images/Hand Gloves.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"Gloves",
    },
    {
        title:"Hand Gloves",
        image:"images/Hand Gloves.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"Gloves",
    },
    {
        title:"Hand Gloves",
        image:"images/Hand Gloves.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"Gloves",
    },
    {
        title:"Hand Gloves",
        image:"images/Hand Gloves.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"Gloves",
    },
    {
        title:"Hand Gloves",
        image:"images/Hand Gloves.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"Gloves",
    },
    {
        title:"Hand Gloves",
        image:"images/Hand Gloves.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"Gloves",
    },
    {
        title:"Hand Gloves",
        image:"images/Hand Gloves.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"Gloves",
    },
    {
        title:"Hand Gloves",
        image:"images/Hand Gloves.png",
        size:"500ml",
        rating:"4.5",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolorem omnis iure enim totam voluptatem amet vel reprehenderit quia laudantium.",
        price:"54 Tk",
        oldprice:"59 TK",
        category:"Gloves",
    },
]

export default ProCard